name: EDTEAM FastAPI demo

on:
  push:
   branches:
     - master
     - develop
 jobs:
  ci:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout
        uses: actions/checkout@v4   

      - name: install dependencies
        run: |
         pip3 install -r requirements.txt

      - name: unittest
        run: |
          pytest test/test.py

      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME1}}/edteam-fastapi-demo:${ github.sha } .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME1 }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
            
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME1}}/edteam-fastapi-demo:${ github.sha }     